pub(crate) mod conservation;
pub(crate) mod free;
pub(crate) mod instability;
pub(crate) mod landau;
pub(crate) mod plummer;
pub(crate) mod spherical;
pub(crate) mod stability;
pub(crate) mod uniform;
pub(crate) mod zeldovich;
